stocks_dbt_model:
  outputs:
    dev:
      dbname: StockDB
      #old localhost
      host: 127.0.0.1
      pass: eng_acct
      port: 5432
      schema: NASDAQ
      threads: 4
      type: postgres
      user: eng_acct
  target: dev
