version: 2

models:
  - name: stocks_dbt_model
    description: "Data model for S&P 500 Stocks"
    database: StockDB
    schema: NASDAQ
    tables:
      - name: ticker_daily_prices
        description: Fact table for daily stock prices
      - name: ticker_earnings_reports
        description: Fact table for earnings reports
      - name: s_and_p_500_history
        description: Fact table containing all tickers historically listed in S&P 500
      - name: ticker_profiles
        description: Dimension table with ticker profile information
      - name: industry_codes
        description: Dimension table wih Zacks/FC industry codes for each ticker
      - name: sector_codes
        description: Dimension table with Zacks/FC expanded sector codes for each ticker
      - name: zacks_fc_api
        description: API resposne + Generated Surrogate Key
      - name: wiki_prices_api
        description: API response


sources:
  - name: landing
    schema: LANDINGS
    database: StockDB
    tables:
      - name: wiki_prices_api
      - name: zacks_fc_api
  - name: nasdaq
    schema: NASDAQ
    database: StockDB
    tables:
      - name: s_and_p_500_history



